version: '3.1'

services:

  dbMysql:
    image: mysql:8.0.3
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mydb
      

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
      
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"