server:
  port: 8081
spring:
   cloud:
    config:
      server:
        git:
          uri: https://github.com/sidharthdec/justcreated/
          searchPaths: democonfig
          username: sidharthdec@gmail.com
          password: citi1792
           
            

    
   