server:
  port: 8081 

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/sidharthdec/justcreated/"
          search-paths: democonfig
          username: "sidharthdec@gmail.com"
          password: "citi1792"
           
            

    
   