tracer:
property: I AM THE DEV
spring:
jpa:
properties:
hibernate:
dialect: org.hibernate.dialect.PostgreSQLDialect
database: POSTGRESQL
datasource:
platform: postgres
url: jdbc:postgresql://database:5432/eagle_eye_local
username: postgres
password: p0stgr@s
testWhileIdle: true
validationQuery: SELECT 1
show-sql: true
driverClassName: org.postgresql.Driver