server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include: health
 
spring:
   cloud:
    config:
      server:
        git:
          uri: https://github.com/sidharthdec/justcreated
          searchPaths: configs/configs
          username: sidharthdec@gmail.com
          password: citi1792