spring:
  datasource:
        url: jdbc:mysql://localhost:3306/mydb??verifyServerCertificate=false&
                         autoReconnect=true&
                         useSSL=false"
        username: root
        password: changeme
        driver-class-name: com.mysql.jdbc.Driver
    
    
server.port : 8383
                         
                         
    
    
